services:
    server:
        image: ghcr.io/redstonewizard08/mayhem:latest
        # build:
        #     context: .
        environment:
            HOST: 0.0.0.0
            PORT: 4000
            DB_USER: mayhem
            DB_PASS: mayhem
            DB_HOST: database
            DB_PORT: 5432
            DB_NAME: mayhem
        networks:
            - mayhem_net
        links:
            - database
        ports:
            - 4000:4000
            - 4001:4001
        expose:
            - 4000
            - 4001
        
    database:
        image: postgres:15-alpine
        environment:
            - POSTGRES_USER=mayhem
            - POSTGRES_PASSWORD=mayhem
            - POSTGRES_DB=mayhem
        volumes:
            - db_data:/var/lib/postgresql/data
        logging:
          driver: none
        networks:
            - mayhem_net

volumes:
    db_data:

networks:
    mayhem_net:
