[default]
address = "0.0.0.0"
port = 4001

[default.databases.dev_db]
url = "postgresql://mayhem:mayhem@127.0.0.1:5432/mayhem_dev"

min_connections = 64
max_connections = 1024
connect_timeout = 5
idle_timeout = 120
