[package]
name = "mayhemctl"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.22", features = ["debug", "env", "derive", "cargo", "string"] }
git2 = "0.15.0"
lazy_static = "1.4.0"
path-absolutize = "3.0.14"
question = "0.2.2"
structopt = "0.3.26"
