name: ESLint

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    schedule:
        - cron: "20 13 * * 3"

jobs:
    eslint:
        name: Run eslint scanning
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 7
                  run_install: false

            - name: Install ESLint
              run: |
                  pnpm add -w eslint@8.10.0
                  pnpm add -w @microsoft/eslint-formatter-sarif@2.1.7

            - name: Run ESLint
              run: |
                  npx eslint . \
                    --config .eslintrc.cjs \
                    --ext .js,.jsx,.ts,.tsx,.svelte \
                    --format @microsoft/eslint-formatter-sarif \
                    --output-file eslint-results.sarif
              continue-on-error: true

            - name: Upload analysis results to GitHub
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: eslint-results.sarif
                  wait-for-processing: true
